Rewrote User Model, Schema and Resolver
Coding-Coach/coding-coach-api pull request #20
Opened 2018-10-19 19:44 UTC by gibsonhan

Wasn't too smart on the first one. Coded without a dev server active. It builds now.
Aside from that I have set Date fields in GraphQl to value of String. 
Will resolve this when I get the chance.
Working build. 
Have yet to remove dummy data in graphql

2018-10-23 17:50 UTC, gibsonhan commented
@charlesjliu  @jagzviruz , I summon thee for thou code review

2018-10-24 16:27 UTC, charlesjliu requested changes
looks good so far. hook it up to mongo!

2018-10-24 16:27 UTC, charlesjliu commented on src/resolvers/user.js
> +    test: () => 'testing the resolver',
don't forget to remove this

2018-10-24 16:27 UTC, charlesjliu commented on src/resolvers/user.js
> +    usersList: () => usersDb,
let's rename this to: `getUsers`. it makes more sense what the query is going to do when it's more declarative

2018-10-24 16:27 UTC, charlesjliu commented on src/resolvers/user.js
> +    userByID: (root, { id }) => {
let's rename to `getUser`

2018-10-24 16:27 UTC, charlesjliu commented on src/resolvers/user.js
> +  Query: {
Make your resolvers get a user/users from mongo next

2018-10-24 16:27 UTC, charlesjliu commented on src/resolvers/user.js
> +  User: {
these look like a one-to-one mapping, you don't need separate field resolvers for each field of `User`. `apollo` will handle it

2018-10-24 22:48 UTC, gibsonhan commented on src/resolvers/user.js
> +    test: () => 'testing the resolver',
purged

2018-10-24 23:43 UTC, gibsonhan commented on src/resolvers/user.js
> +    usersList: () => usersDb,
declarative also helps with the FE because they easily know what they are query by naming convention too right?

2018-10-24 23:45 UTC, gibsonhan commented on src/resolvers/user.js
> +  User: {
Didn not know that about apollo. Will remove.

2018-10-25 00:18 UTC, gibsonhan commented
How exactly do we connect it to the mongo?  do we have an url for an actual db?

2018-10-25 00:19 UTC, gibsonhan commented on src/resolvers/user.js
> +  Query: {
I am unsure what this means @charlesjliu  can you clarify what you mean "resolvers get a user/users from mongo next"

2018-10-25 15:19 UTC, jagzviruz commented
> How exactly do we connect it to the mongo? do we have an url for an actual db?

Setting up mongo inside the docker container can be one way to go. Otherwise, you can assume the developer machine has a local instance of mongo installed. Update the README.md accordingly.

You can use a `.env` file to configure these settings, and add a sample `.env.sample` file.

2018-10-26 16:32 UTC, charlesjliu commented
@gibsonhan as @jagzviruz pointed out, you can spin up mongo in a docker container. it's specified in our docker-compose.yml. I think running `docker-compose start mongo` should work.

2018-10-28 05:38 UTC, closed without merging